package co.edu.uniquindio.compiladores.lexico

enum class Categoria {
    PALABRA_RESERVADA, ENTERO, DECIMAL, IDENTIFICADOR, OPERADOR_ARITMETICO, OPERADOR_LOGICO, OPERADOR_ASIGNACION,
    OPERADOR_INCREMETO, OPERADOR_DECREMENTO, OPERADOR_RELACIONAL, PARENTESIS_IZQUIERDO, PARENTESIS_DERECHO,
    LLAVE_IZQUIERDO, LLAVE_DERECHO, CORCHETE_IZQUIERDO, CORCHETE_DERECHO, FIN_SENTENCIA, PUNTO, DOS_PUNTOS,
    SEPARADOR, COMENTARIO_LINEA, COMENTARIO_BLOQUE, CADENA_CARCTERES, CARACTER, DESCONOCIDO
}